//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhaptics.SDK2
{
    using System;
    using UnityEngine;
    
    
    public class BhapticsEvent
    {
        
        public const string WRONG_LEFT = "wrong_left";
        
        public const string HIT_EXCELLENT_RIGHT = "hit_excellent_right";
        
        public const string BABYDRIVER = "babydriver";
        
        public const string GAME_START = "game_start";
        
        public const string HIT_CORRECT_LEFT = "hit_correct_left";
        
        public const string WRONG_RIGHT = "wrong_right";
        
        public const string HIT_CORRECT_RIGHT = "hit_correct_right";
        
        public const string HIT_EXCELLENT_LEFT = "hit_excellent_left";
    }
}
